// Generated by CoffeeScript 2.0.0
void function () {
  var mapped, one;
  Array.prototype.map = function (iterator) {
    return function (accum$) {
      var index, item;
      for (var i$ = 0, length$ = this.length; i$ < length$; ++i$) {
        item = this[i$];
        index = i$;
        accum$.push(iterator.call(item, index));
      }
      return accum$;
    }.call(this, []);
  };
  one = [
    1,
    2,
    3
  ];
  mapped = one.map(function (item) {
    return item * 2;
  });
  console.log(mapped);
}.call(this);

//# sourceMappingURL=test.js.map
